volumes:
  postgres_volume:

services:
  grpc-server:
    build:
      context: .
      dockerfile: grpc-server.Dockerfile
    env_file: ".env"
    ports:
      - "${GRPC_SERVER_PORT}:${GRPC_SERVER_PORT}"
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:17.4-alpine3.21
    environment:
      - "POSTGRES_DB=${PG_DB_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "4321:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB_NAME}" ]
      interval: 3s
      timeout: 3s
      retries: 10

  migrator:
    build:
      context: .
      dockerfile: migrator.Dockerfile
    restart: on-failure
    env_file: ".env"